### ISSUE TITLE
[Fix] v1.1.0을 위한 나머지 UI 수정 작업

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#192]
### 📝 작업 목적
| ⚒️ Title | `v1.1.0을 위한 나머지 UI 수정 작업` | 
| :--- | :--- |
| 📜 **Description** | description |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

#### All Views
- [x] 모든 내비툴바 심볼 및 타이틀 bold로 변경

#### ConversationView
- [x]  C10-10 톡버튼 애니메이션 없어야함.
    - C10-10, C11-10에서만 애니메이션 없고 C10-30, C10-40에서는 애니메이션 되어야 해요.
- [x]  C10-10, C10-30 버튼 내부에 C10-40과 같이 쉐브론 들어가도록 변경됨.
    - 버그나 스펙이 안맞아서가 아니고 UX개선에 의함입니다!
- [ ]  C11-13 확인해주기
    - 이전 답변이 없을 경우 텅 멘트가 opacity0.5로 들어감.

#### HistoryListView
- [ ]  검색 취소버튼 텍필 트랜지션 끝나고 뜨게끔 딜레이 적용
- [x] BDText 적용
#### All SettingsView 
- [x] BDText 적용

**Comment by ValseLee** [comment]
Toss, 송금을 쉽게

**Comment by lianne-b** [comment]
> Toss, 송금을 쉽게

❓
