### ISSUE TITLE
[HotFix] Moca와 함께하는 인터널 쇼케이스 퀵 피드백 반영

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#60]
### 📝 작업 목적
| ⚒️ Title | `Moca와 함께하는 인터널 쇼케이스 퀵 피드백 반영` | 
| :--- | :--- |
| 📜 **Description** | 인터널 쇼케이스를 위한 퀵 피드백 내용을 반영합니다. |

---

**Comment by alpaka99** [comment]
고생많으셨습니다!
